version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: market
    ports:
      - 5432:5432

  backend:
    build:
      context: ./backend
    ports:
      - 8000:8000
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
